import type { CreditCardSeed } from '../types'

export const creditCardsBatchB = [
  {
    id: 'bca-ultimate',
    name: 'BCA Visa Infinite',
    shortName: 'BCA Visa Infinite',
    bank: 'BCA',
    network: 'Visa',
    tier: 'Infinite',
    annualFee: 1_500_000,
    minIncome: 50_000_000,
    image: 'https://picsum.photos/seed/bca-ultimate/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 2 },
      overseas: { spend: 10_000, points: 2 },
      dining: { spend: 10_000, points: 2 },
      online: { spend: 10_000, points: 2 },
      travel: { spend: 10_000, points: 2 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 6, milesReceived: 1 },
      { program: 'Asia Miles', pointsRequired: 6, milesReceived: 1 },
    ],
    benefits: { lounge: true, insurance: true, transfer: true },
    pros: [
      '2x poin semua transaksi',
      'Lounge access',
      'Airport transfer',
      'Travel insurance komprehensif',
    ],
    cons: [
      'Annual fee sangat tinggi',
      'Conversion ratio 6:1',
      'Min income Rp50 juta',
    ],
    bestFor: 'High spender yang menghargai benefit premium',
    notIdealFor: 'Yang fokus kumpulkan miles efisien',
  },
  {
    id: 'cimb-travelworld',
    name: 'CIMB TravelWorld Visa Platinum',
    shortName: 'CIMB TravelWorld',
    bank: 'CIMB',
    network: 'Visa',
    tier: 'Platinum',
    annualFee: 350_000,
    minIncome: 8_000_000,
    image: 'https://picsum.photos/seed/cimb-travel/400/250.jpg',
    earningRates: {
      local: { spend: 20_000, points: 1 },
      overseas: { spend: 10_000, points: 1 },
      dining: { spend: 20_000, points: 1 },
      online: { spend: 20_000, points: 1 },
      travel: { spend: 10_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 2, milesReceived: 1 },
      { program: 'KrisFlyer', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: false, transfer: false },
    pros: [
      'Annual fee paling rendah',
      'Min income rendah',
      'Dua transfer partner',
    ],
    cons: [
      'Earning rate sangat rendah',
      'Tidak ada benefit travel',
      'Conversion 2:1',
    ],
    bestFor: 'Budget traveler yang mulai belajar miles',
    notIdealFor: 'Yang ingin kumpulkan miles cepat',
  },
  {
    id: 'danamon-go-green',
    name: 'Danamon GO Green Visa Platinum',
    shortName: 'Danamon GO Green',
    bank: 'Danamon',
    network: 'Visa',
    tier: 'Platinum',
    annualFee: 400_000,
    minIncome: 10_000_000,
    image: 'https://picsum.photos/seed/danamon-green/400/250.jpg',
    earningRates: {
      local: { spend: 15_000, points: 1 },
      overseas: { spend: 10_000, points: 1 },
      dining: { spend: 15_000, points: 1 },
      online: { spend: 15_000, points: 1 },
      travel: { spend: 10_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 3, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: false, transfer: false },
    pros: ['Annual fee terjangkau', 'Overseas earning rate oke'],
    cons: [
      'Conversion 3:1 kurang kompetitif',
      'Tidak ada lounge',
      'Min transfer partner',
    ],
    bestFor: 'Pengguna yang transaksi overseas sesekali',
    notIdealFor: 'Collector miles serius',
  },
  {
    id: 'ocbc-nsp-platinum',
    name: 'OCBC Nokia Series Platinum',
    shortName: 'OCBC NSP Platinum',
    bank: 'OCBC',
    network: 'Mastercard',
    tier: 'Platinum',
    annualFee: 500_000,
    minIncome: 15_000_000,
    image: 'https://picsum.photos/seed/ocbc-nsp/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 1 },
      overseas: { spend: 5_000, points: 1 },
      dining: { spend: 5_000, points: 1 },
      online: { spend: 10_000, points: 1 },
      travel: { spend: 5_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 2, milesReceived: 1 },
      { program: 'KrisFlyer', pointsRequired: 2, milesReceived: 1 },
      { program: 'Asia Miles', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: false, transfer: false },
    pros: [
      'Earning rate overseas & dining sangat baik',
      'Banyak transfer partner',
      'Annual fee reasonable',
    ],
    cons: [
      'Tidak ada lounge access',
      'Local earning rate standar',
      'Min income Rp15 juta',
    ],
    bestFor: 'Foodie dan traveler yang sering overseas',
    notIdealFor: 'Yang butuh lounge dan benefit premium',
  },
] satisfies CreditCardSeed[]
