import type { CreditCardSeed } from '../types'

export const creditCardsBatchA = [
  {
    id: 'bca-krisflyer-visa-infinite',
    name: 'BCA Singapore Airlines KrisFlyer Visa Infinite',
    shortName: 'BCA KrisFlyer Infinite',
    bank: 'BCA',
    network: 'Visa',
    tier: 'Infinite',
    annualFee: 1_000_000,
    minIncome: 50_000_000,
    image: 'https://picsum.photos/seed/bca-krisflyer-vi/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 1 },
      overseas: { spend: 5_000, points: 1 },
      dining: { spend: 10_000, points: 1 },
      online: { spend: 10_000, points: 1 },
      travel: { spend: 5_000, points: 1 },
    },
    transferPartners: [
      { program: 'KrisFlyer', pointsRequired: 1, milesReceived: 1 },
    ],
    benefits: { lounge: true, insurance: true, transfer: false },
    pros: [
      'Transfer 1:1 ke KrisFlyer',
      'Lounge access gratis',
      'Earning rate overseas sangat baik',
    ],
    cons: [
      'Annual fee Rp1 juta',
      'Min income Rp50 juta',
      'Local earning rate standar',
    ],
    bestFor: 'Traveler sering overseas dan loyal Singapore Airlines',
    notIdealFor: 'Pengguna mayoritas transaksi lokal',
  },
  {
    id: 'citi-premiermiles',
    name: 'Citi PremierMiles Visa Signature',
    shortName: 'Citi PremierMiles',
    bank: 'Citibank',
    network: 'Visa',
    tier: 'Signature',
    annualFee: 750_000,
    minIncome: 30_000_000,
    image: 'https://picsum.photos/seed/citi-premier/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 1 },
      overseas: { spend: 6_000, points: 1 },
      dining: { spend: 10_000, points: 1 },
      online: { spend: 10_000, points: 1 },
      travel: { spend: 6_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 2, milesReceived: 1 },
      { program: 'KrisFlyer', pointsRequired: 2, milesReceived: 1 },
      { program: 'Asia Miles', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: true, transfer: false },
    pros: [
      'Banyak transfer partner',
      'Annual fee lebih terjangkau',
      'Earning rate overseas baik',
    ],
    cons: [
      'Tidak ada lounge access',
      'Conversion ratio 2:1',
      'Min income masih tinggi',
    ],
    bestFor: 'Fleksibilitas transfer ke banyak program miles',
    notIdealFor: 'Yang butuh lounge access gratis',
  },
  {
    id: 'bri-krisflyer-platinum',
    name: 'BRI Singapore Airlines KrisFlyer Visa Platinum',
    shortName: 'BRI KrisFlyer Platinum',
    bank: 'BRI',
    network: 'Visa',
    tier: 'Platinum',
    annualFee: 500_000,
    minIncome: 10_000_000,
    image: 'https://picsum.photos/seed/bri-krisflyer/400/250.jpg',
    earningRates: {
      local: { spend: 15_000, points: 1 },
      overseas: { spend: 8_000, points: 1 },
      dining: { spend: 15_000, points: 1 },
      online: { spend: 15_000, points: 1 },
      travel: { spend: 8_000, points: 1 },
    },
    transferPartners: [
      { program: 'KrisFlyer', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: false, transfer: false },
    pros: ['Annual fee rendah', 'Min income sangat rendah', 'Cocok pemula'],
    cons: ['Earning rate rendah', 'Tidak ada lounge', 'Conversion 2:1'],
    bestFor: 'Pemula yang mulai kumpulkan KrisFlyer miles',
    notIdealFor: 'Traveler premium yang butuh benefit lengkap',
  },
  {
    id: 'mandiri-garuda-platinum',
    name: 'Mandiri Garuda Indonesia Visa Platinum',
    shortName: 'Mandiri Garuda Platinum',
    bank: 'Mandiri',
    network: 'Visa',
    tier: 'Platinum',
    annualFee: 500_000,
    minIncome: 10_000_000,
    image: 'https://picsum.photos/seed/mandiri-garuda/400/250.jpg',
    earningRates: {
      local: { spend: 15_000, points: 1 },
      overseas: { spend: 10_000, points: 1 },
      dining: { spend: 10_000, points: 1 },
      online: { spend: 15_000, points: 1 },
      travel: { spend: 10_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: false, transfer: false },
    pros: [
      'Langsung ke GarudaMiles',
      'Annual fee terjangkau',
      'Dining earning rate baik',
    ],
    cons: [
      'Tidak bisa transfer ke program lain',
      'Tidak ada lounge',
      'Local earning rate rendah',
    ],
    bestFor: 'Pengguna setia Garuda Indonesia',
    notIdealFor: 'Yang butuh fleksibilitas transfer miles',
  },
] satisfies CreditCardSeed[]
