import type { CreditCardSeed } from '../types'

export const creditCardsBatchC = [
  {
    id: 'uob-prvi-miles',
    name: 'UOB PRVI Miles Visa Signature',
    shortName: 'UOB PRVI Miles',
    bank: 'UOB',
    network: 'Visa',
    tier: 'Signature',
    annualFee: 800_000,
    minIncome: 30_000_000,
    image: 'https://picsum.photos/seed/uob-prvi/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 1.2 },
      overseas: { spend: 10_000, points: 2 },
      dining: { spend: 10_000, points: 1.2 },
      online: { spend: 10_000, points: 1.2 },
      travel: { spend: 10_000, points: 2 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 2, milesReceived: 1 },
      { program: 'KrisFlyer', pointsRequired: 2, milesReceived: 1 },
      { program: 'Asia Miles', pointsRequired: 2, milesReceived: 1 },
      { program: 'Emirates Skywards', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: true, transfer: false },
    pros: [
      '1.2x poin lokal, 2x overseas/travel',
      '4 transfer partner',
      'Travel insurance',
    ],
    cons: ['Tidak ada lounge', 'Conversion 2:1', 'Annual fee cukup tinggi'],
    bestFor: 'Traveler yang sering overseas dan butuh fleksibilitas',
    notIdealFor: 'Yang fokus transaksi lokal saja',
  },
  {
    id: 'hsbc-premier',
    name: 'HSBC Premier Mastercard',
    shortName: 'HSBC Premier',
    bank: 'HSBC',
    network: 'Mastercard',
    tier: 'Premier',
    annualFee: 1_250_000,
    minIncome: 50_000_000,
    image: 'https://picsum.photos/seed/hsbc-premier/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 1 },
      overseas: { spend: 5_000, points: 1 },
      dining: { spend: 10_000, points: 1 },
      online: { spend: 10_000, points: 1 },
      travel: { spend: 5_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 2, milesReceived: 1 },
      { program: 'KrisFlyer', pointsRequired: 2, milesReceived: 1 },
      { program: 'Asia Miles', pointsRequired: 2, milesReceived: 1 },
      { program: 'British Airways', pointsRequired: 2, milesReceived: 1 },
    ],
    benefits: { lounge: true, insurance: true, transfer: true },
    pros: [
      'Lounge access global',
      'Airport transfer',
      '5 transfer partner',
      'Earning rate overseas sangat baik',
    ],
    cons: ['Annual fee tinggi', 'Harus jadi nasabah Premier', 'Conversion 2:1'],
    bestFor: 'Nasabah HSBC Premier yang sering travel internasional',
    notIdealFor: 'Non-nasabah HSBC',
  },
  {
    id: 'bca-mcard-platinum',
    name: 'BCA Mastercard Black',
    shortName: 'BCA Mastercard Black',
    bank: 'BCA',
    network: 'Mastercard',
    tier: 'Black',
    annualFee: 1_200_000,
    minIncome: 30_000_000,
    image: 'https://picsum.photos/seed/bca-mcard-blk/400/250.jpg',
    earningRates: {
      local: { spend: 10_000, points: 1 },
      overseas: { spend: 5_000, points: 1 },
      dining: { spend: 10_000, points: 1 },
      online: { spend: 10_000, points: 1 },
      travel: { spend: 5_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 5, milesReceived: 1 },
      { program: 'KrisFlyer', pointsRequired: 5, milesReceived: 1 },
    ],
    benefits: { lounge: true, insurance: true, transfer: true },
    pros: ['Lounge access', 'Airport transfer', 'Earning rate overseas baik'],
    cons: [
      'Conversion 5:1 sangat buruk untuk miles',
      'Annual fee tinggi',
      'Lebih cocok untuk cashback',
    ],
    bestFor: 'Yang menghargai benefit lifestyle, bukan miles collector',
    notIdealFor: 'Yang fokus kumpulkan miles efisien',
  },
  {
    id: 'mega-travel-card',
    name: 'Mega Travel Card Visa Platinum',
    shortName: 'Mega Travel Card',
    bank: 'Mega',
    network: 'Visa',
    tier: 'Platinum',
    annualFee: 300_000,
    minIncome: 5_000_000,
    image: 'https://picsum.photos/seed/mega-travel/400/250.jpg',
    earningRates: {
      local: { spend: 20_000, points: 1 },
      overseas: { spend: 15_000, points: 1 },
      dining: { spend: 20_000, points: 1 },
      online: { spend: 20_000, points: 1 },
      travel: { spend: 15_000, points: 1 },
    },
    transferPartners: [
      { program: 'GarudaMiles', pointsRequired: 3, milesReceived: 1 },
    ],
    benefits: { lounge: false, insurance: false, transfer: false },
    pros: ['Annual fee sangat murah', 'Min income sangat rendah'],
    cons: [
      'Earning rate sangat rendah',
      'Conversion 3:1',
      'Tidak ada benefit travel',
    ],
    bestFor: 'Pemula dengan budget terbatas',
    notIdealFor: 'Siapa pun yang serius kumpulkan miles',
  },
] satisfies CreditCardSeed[]
