/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CreditCardsIndexRouteImport } from './routes/credit-cards/index'
import { Route as ReviewsSubCategoryRouteImport } from './routes/reviews/$subCategory'
import { Route as CreditCardsSlugRouteImport } from './routes/credit-cards/$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsIndexRoute = CreditCardsIndexRouteImport.update({
  id: '/credit-cards/',
  path: '/credit-cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSubCategoryRoute = ReviewsSubCategoryRouteImport.update({
  id: '/reviews/$subCategory',
  path: '/reviews/$subCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsSlugRoute = CreditCardsSlugRouteImport.update({
  id: '/credit-cards/$slug',
  path: '/credit-cards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/consulting': typeof ConsultingRoute
  '/deals': typeof DealsRoute
  '/guides': typeof GuidesRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/quiz': typeof QuizRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/credit-cards/$slug': typeof CreditCardsSlugRoute
  '/reviews/$subCategory': typeof ReviewsSubCategoryRoute
  '/credit-cards/': typeof CreditCardsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/consulting': typeof ConsultingRoute
  '/deals': typeof DealsRoute
  '/guides': typeof GuidesRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/quiz': typeof QuizRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/credit-cards/$slug': typeof CreditCardsSlugRoute
  '/reviews/$subCategory': typeof ReviewsSubCategoryRoute
  '/credit-cards': typeof CreditCardsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/consulting': typeof ConsultingRoute
  '/deals': typeof DealsRoute
  '/guides': typeof GuidesRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/quiz': typeof QuizRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/credit-cards/$slug': typeof CreditCardsSlugRoute
  '/reviews/$subCategory': typeof ReviewsSubCategoryRoute
  '/credit-cards/': typeof CreditCardsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/compare'
    | '/consulting'
    | '/deals'
    | '/guides'
    | '/membership'
    | '/news'
    | '/newsletter'
    | '/quiz'
    | '/articles/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/credit-cards/$slug'
    | '/reviews/$subCategory'
    | '/credit-cards/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/compare'
    | '/consulting'
    | '/deals'
    | '/guides'
    | '/membership'
    | '/news'
    | '/newsletter'
    | '/quiz'
    | '/articles/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/credit-cards/$slug'
    | '/reviews/$subCategory'
    | '/credit-cards'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/compare'
    | '/consulting'
    | '/deals'
    | '/guides'
    | '/membership'
    | '/news'
    | '/newsletter'
    | '/quiz'
    | '/articles/$slug'
    | '/auth/login'
    | '/auth/register'
    | '/credit-cards/$slug'
    | '/reviews/$subCategory'
    | '/credit-cards/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  ConsultingRoute: typeof ConsultingRoute
  DealsRoute: typeof DealsRoute
  GuidesRoute: typeof GuidesRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  NewsletterRoute: typeof NewsletterRoute
  QuizRoute: typeof QuizRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CreditCardsSlugRoute: typeof CreditCardsSlugRoute
  ReviewsSubCategoryRoute: typeof ReviewsSubCategoryRoute
  CreditCardsIndexRoute: typeof CreditCardsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards/': {
      id: '/credit-cards/'
      path: '/credit-cards'
      fullPath: '/credit-cards/'
      preLoaderRoute: typeof CreditCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$subCategory': {
      id: '/reviews/$subCategory'
      path: '/reviews/$subCategory'
      fullPath: '/reviews/$subCategory'
      preLoaderRoute: typeof ReviewsSubCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards/$slug': {
      id: '/credit-cards/$slug'
      path: '/credit-cards/$slug'
      fullPath: '/credit-cards/$slug'
      preLoaderRoute: typeof CreditCardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  ConsultingRoute: ConsultingRoute,
  DealsRoute: DealsRoute,
  GuidesRoute: GuidesRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  NewsletterRoute: NewsletterRoute,
  QuizRoute: QuizRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CreditCardsSlugRoute: CreditCardsSlugRoute,
  ReviewsSubCategoryRoute: ReviewsSubCategoryRoute,
  CreditCardsIndexRoute: CreditCardsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
